-- ========================================================
-- SQL Dump created from Excel: Copy of Membership Form
-- Exported on: 2026-07-21 09:50:57
-- Total Records: 74
-- ========================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- --------------------------------------------------------
-- Table structure for `membership_form_responses`
-- --------------------------------------------------------
DROP TABLE IF EXISTS `membership_form_responses`;
CREATE TABLE `membership_form_responses` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `timestamp` DATETIME NULL,
  `full_name` VARCHAR(255) NULL,
  `designation` VARCHAR(255) NULL,
  `business_name` VARCHAR(255) NULL,
  `business_category` VARCHAR(255) NULL,
  `mobile` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `business_address` TEXT NULL,
  `address_area` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `native_city` VARCHAR(255) NULL,
  `birth_date` DATE NULL,
  `anniversary_date` DATE NULL,
  `business_introduction` TEXT NULL,
  `profile_picture_url` TEXT NULL,
  `business_logo_url` TEXT NULL,
  `payment_attachment_url` TEXT NULL,
  `residence_address_area` VARCHAR(255) NULL,
  `document_folder_status` VARCHAR(255) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Data for `membership_form_responses`
-- --------------------------------------------------------
INSERT INTO `membership_form_responses` (`id`, `timestamp`, `full_name`, `designation`, `business_name`, `business_category`, `mobile`, `email`, `business_address`, `address_area`, `city`, `native_city`, `birth_date`, `anniversary_date`, `business_introduction`, `profile_picture_url`, `business_logo_url`, `payment_attachment_url`, `residence_address_area`, `document_folder_status`) VALUES
(1, '2025-10-11 21:52:00', 'TAPAN CHAUHAN', 'CERTIFIED FINANCIAL GOAL PLANNER', 'CT FINANCIAL SERVICES', 'INVESTMENT & INSURANCE', '9537733567', 'chauhantapan42@gmail.com', '1002, SHIVALIK SHILP, ISCON CROSS ROAD, S G Highway', 'AHMEDABAD', 'AHMEDABAD', 'SURENDRANAGAR', '1989-01-31', '2013-12-08', 'I AM CERTIFIED FINANCIAL GOAL PLANNER FROM AMERICAN ACADEMY OF FINANCIAL PLANNING, MDRT USA. 

EXPERTS IN FINANCIAL PLANNING OF CHILD EDUCATION, 
CHILD MARRIAGE FINANCIAL PLANNING, 
RETIREMENT FINANCIAL PLANNING, 
PENSION PLANNING. 

Your A to Z Financial planning at one point of contact and one stop solution for your all future financial Responsibility.', 'https://drive.google.com/open?id=1OdFKjwYQ9F905XgkjtL3sANS2-tpqzBR', 'https://drive.google.com/open?id=11jQyLJSbwTVwaXv16hqvOh46ivAH9Zh6', 'https://drive.google.com/open?id=128ffCJ3YEta4eIAQ_LWlpx5VD9EXWf7A', NULL, 'Done (Reg. Fess SS Pending)'),
(2, '2025-10-12 10:50:24', 'TARBUNDIYA JAYDEEP RAMESHBHAI', NULL, 'Green Power Solar', 'Service', '8156097059', 'j.dalwadi12@gmail.com', '34, Shri Hari Bungalow, Bavla, Ahmedabad', 'Bavla', 'Bavla', 'Halvad', '1998-07-04', '2025-02-07', 'Solar panel installation 
Residential 
Commercial 
Industrial', 'https://drive.google.com/open?id=1yfYY-d9mEX1cohWT0x0F0dJuycSQ5LeX', 'https://drive.google.com/open?id=1XYJqEVb_mJZrpb6rOGoU1sZPQmFxdPcV', 'https://drive.google.com/open?id=1fW8c43smqhnF74qoeMxZdGH5D5Oc2j5o', NULL, 'Done'),
(3, '2025-10-12 10:53:04', 'Harmish Lakum', 'Assistant Manager - International Business', 'Torrent Pharma', 'Pharma', '8866261699', 'hlakum01@gmail.com', 'Ahmedabad', 'Thaltej', 'Ahmedabad', 'Surendranagar', '2002-06-14', NULL, 'Working at Torrent Pharma as assistant manager in international operations department looking after US and Europe business.', 'https://drive.google.com/open?id=1r-BCtfHZ_iOkvP8EeOTbGrmvragHqzbM', 'https://drive.google.com/open?id=1mfEqgGIoyxCFEp56iP7pcV2PMbv-kUkq', 'https://drive.google.com/open?id=1yGhtTnhAmXoWx9sIrFdMYRh7vXg96uW-', NULL, 'Done'),
(4, '2025-10-12 11:09:27', 'Kaushik Mansukhbhai Chavada', 'Managing Partner', 'Fernweh Vacations', 'Travel', '8401938028', 'kaushik@fernwehvacations.com', '4THF,  406, Shilp Satved, Nr. Sindhu Bhavan hall, Sindhu Bhavan road, Bodakdev', 'Sindhu Bhavan', 'Ahmedabad', 'Limbdi', '1986-09-26', '2012-12-06', 'Fernweh Vacations is an IATA approved travel agency since 2007 head office at Ahmedabad. We are specialize in Domestic & International Air ticket booking, Tour Packages, Visa & Passport formality, Car Rental and Hotel booking around the world.  As well as we do organized Corporate Events and destinations weddings too.', 'https://drive.google.com/open?id=1A5ZbRU9nu4w8eXQqQgjZkwlruWv975eu', 'https://drive.google.com/open?id=17Lq2CjaQfOUxRtTs_nLLC2M2y4AvVfF-', 'https://drive.google.com/open?id=1e9v07a35imo524ObYgSNYQ9tQ3LUbnL3', NULL, 'Done'),
(5, '2025-10-12 11:29:34', 'Mayurkumar Himmatlal Chavda', 'Software engineer', 'HP', 'Engineering', '9035419518', 'mayurchavda87@gmail.com', 'Whitefield, Bangalore', 'Turquoise Blu, Opp Sarathya, Shela', 'Ahmedabad', 'Limbdi', '1987-05-08', '2021-11-21', 'WAN (Wide Area Network) optimization is about improving the performance, reliability, and efficiency of data communication across geographically dispersed sites (e.g. branch offices, clouds, DCs)', 'https://drive.google.com/open?id=1QuFCFhxf0iSgLiGKXsmEoZ6dUZl0p6xc', 'https://drive.google.com/open?id=1Ka5Ic4GnibrstduL2Yn0dnDuG6LxN9im', 'https://drive.google.com/open?id=1QrwvU3SCPoKNid-VcOAtxY_X533VapoZ', NULL, 'Done'),
(6, '2025-10-12 11:39:22', 'Dharmesh Kumar Chavda', 'Partner', 'Veritair', 'Interior Designer and Contractor', '7623948594', 'chavdadharmesh16@gmail.com', 'A-701, Devam, Behind Global International School, Nr. Godrej Garden City,', 'Jagatpur', 'Ahmedabad', 'Botad', '1992-06-16', '1992-06-16', 'We are a Turnkey Interior Contracting team dedicated to transforming houses into dream homes. From concept to completion — we handle everything with precision, quality, and care.
Let’s build spaces that speak style, comfort & elegance.', 'https://drive.google.com/open?id=1uBLFxx2M7_NrVvATfge75Qniv8WAqE_U', 'https://drive.google.com/open?id=15jc1I1M_w2bt_C1UlZacc6r6LseXGPfr', 'https://drive.google.com/open?id=1wT4bHS2pTlvlK2OHe65MXNmThlCpIgva', NULL, 'Done'),
(7, '2025-10-12 12:26:38', 'Dalvadi Vipul karamahibhai', 'Owner', 'Bharvi electricals', 'Service and supply electricals products', '9974707858', 'dalvadivipul1570@gmail.com', '70 Harihar park opp.fulvadi society vastral road Ahmedabad 382418', 'Vastral', 'Ahmedabad', 'Vastadi', '1983-11-22', '2009-12-10', 'We are taking the turnkey project and supply of electricals goods and services of all electrical works.', 'https://drive.google.com/open?id=1k7u8Z6V6Ml4uI3SEoX6J62iN92-8qcHV', 'https://drive.google.com/open?id=1CihxzSK05GiMTQXpDcTPAOAFKyNvBK8k', 'https://drive.google.com/open?id=107scd25a9faHQ7UC8EyOU8v7h1Ez0Oni', NULL, 'Done'),
(8, '2025-10-12 12:30:21', 'KANZAREEYA SONAK KANTILAL', 'Director', 'S GLOW INDUSTRIES PVT LTD', 'Menufecturing of led lights', '8264365614', 'kanzariyasonak@gmail.com', 'Rudra industrial estate behind nk estate gatrad dhamtvan road bakrol bujarang Ahmedabad', 'Bakrol bujarang', 'Ahmedabad', 'Ahmedabad', '2000-02-07', NULL, 'Manufacturing plant of all type led lights indoor nd outdoor also sell raw material of led lights', 'https://drive.google.com/open?id=17bXhikYs_TEHBR5War6VaPPwHjjLK-Gn', 'https://drive.google.com/open?id=1-7eSYRpb8gyyU9Cun-MGZTydSlRZD8Ll', 'https://drive.google.com/open?id=1MhM9HXWIsVnTHPbTSnhN658IsUMeGi-Y', NULL, NULL),
(9, '2025-10-12 12:54:26', 'Pankajkumar K Parmar', 'Director', 'Airise Technologies Pvt. Ltd.', 'Mfg. of Air Motor', '9998449688', 'pankaj.satwara@gmail.com', 'R-70, Vibrant Karmbhoomi Ind. Park, Vehlala, Ahmedabad', 'Vehlal', 'Ahmedabad', 'Morbi', '1978-06-14', '2001-05-19', 'Mfg. of Air Motor, Gear Box, Air compressor Parts.', 'https://drive.google.com/open?id=1yjkFA40rj7i4L-8q-rtPz-M7bms_jhPp', 'https://drive.google.com/open?id=1yLX7vWdvuZ_UwKRI_UO-VEXB0HIf-9MJ', 'https://drive.google.com/open?id=186AV_Ko8hXDiWqplUJx1UtdZ_uFX-9AB', NULL, 'Two Time Form Fill'),
(10, '2025-10-12 13:34:15', 'Kavan Dabhi', 'Owner', 'MARKETYFY', 'Digital Marketing', '8488876799', 'kavan45@gmail.com', 'kavandabhi@marketyfy.com', 'Makarba, Ahmedabad', 'Ahmedabad', 'Ahmedabad', '1994-06-10', '2022-01-26', 'We, Marketyfy, are a digital marketing company situated in Ahmedabad with another branch in Vadodara. 
We provide all type of digital marketing services like Google Ads, Meta Ads, Social Media Marketing, SEO, Website development, D2C and SAAS Marketing.', 'https://drive.google.com/open?id=1DYqa44zK91Kxckp2wtYtI61kVA7cJk56', 'https://drive.google.com/open?id=1YIAhNYq-hf1jEpss9sngwCOcSbNlUVNJ', 'https://drive.google.com/open?id=1HgSprgY5u22cZBG-0YTlnh-wHa_DQD7H', NULL, 'Done'),
(11, '2025-10-12 14:45:52', 'Bhavesh Sathwara', 'Managing Director', 'Sathwara InfoTech', 'IT', '7405402826', 'bhaveshsathwara72@gmail.com', '326, Arth Business Center (ABC, Sardar Patel Ring Rd, opp. Torrent Power, Nikol, Ahmedabad, Gujarat 380049', 'Nikol', 'Ahmedabad', 'Ahmedabad', '1997-05-25', '2024-01-28', 'We are Working on Mobile and Web app Development', 'https://drive.google.com/open?id=18BtWk-22RX5Ucr0fYnwnZAuNmA8it0JT', 'https://drive.google.com/open?id=1aw6uNiYQcYKnEPYYm8C7G-L4Nan9lb7r', 'https://drive.google.com/open?id=1TBYNfFwRCwbQMdPopHxIkGIItWEFld9V', NULL, 'Done'),
(12, '2025-10-12 16:07:13', 'Naresh K Satvara', 'CEO & Founder', 'Shree Vinayaka Associate', 'Financial Services (Loan) ( Project Construction Finance, Customise Structured Finance, Raising Equity from PE Funds and AIFs, LRD (Lease Rental Discounting, LAP & Working Capital Loan.', '6357191315', 'naresh.vinayak07@gmail.com', 'Shree Vinayaka Associate   A-524 Fifth Floor, Rosevill Sky Complex , Opp. Croma, Nr. Sukan cross road, Nikol, Ahmedabad - 382350', 'Nr, Kalyan Chowk, Opp Croma - Nikol', 'Ahmedabad', 'Botad', '1980-12-07', '2007-01-21', 'About S V Group

S V Group is a leading financial services and advisory firm, headed by the accomplished and experienced Mr. Naresh K Satvara. With over a decade of expertise in the financial industry — including six years with HDFC Bank Ltd — Mr. Satvara brings in-depth knowledge in structured finance, portfolio management, retail lending, and wholesale real estate debt origination.

At S V Group, we provide a comprehensive range of financial solutions, including debt and equity syndication and strategic financial advisory services. Our team of seasoned professionals, with strong backgrounds in banking, finance, corporate consultancy, and real estate, work collaboratively to deliver innovative financing structures and customized financial models.

We specialize in project appraisal and funding for real estate and infrastructure projects, offering clients tailored solutions to meet their unique financial needs.

Our fully automated and technology-driven operations ensure efficiency, accuracy, and transparency — enabling us to deliver results that consistently exceed client expectations.

At S V Group, our mission is to empower clients with innovative, reliable, and result-oriented financial solutions that support sustainable growth and long-term success.
________________________________________
Financial Services Offered

•	Real Estate Project Construction Finance (Mixed Projects)
•	Project Inventory Funding (Mixed Projects)
•	Redevelopment Project Funding
•	Raising Equity from PE Funds & AIFs
•	External Commercial Borrowing (ECB)
•	Lease Rental Discounting (LRD)
•	Loan Against Property (LAP) & Working Capital Loans
•	Project APF & Home Loans
________________________________________
Types of Projects Handled

Real Estate Projects
•	Residential Developments
•	Commercial Complexes
•	Redevelopment Projects
•	Malls & Multiplexes
•	Warehousing Facilities
•	Hospitals, Hotels & Resorts
•	Educational Institutes (Schools & Colleges)

Miscellaneous Projects
•	Iron & Steel Plants
•	Pharmaceutical Units
•	Paper Mills & Windmills
•	Retail Businesses
________________________________________

S.V. Group’s Core Service Areas

Debt Syndication by Way of:
•	Project Construction Finance
•	Project Inventory Funding
•	External Commercial Borrowing (ECB)
•	Raising Equity from PE Funds (Structured Finance)
•	Lease Rental Discounting (LRD)
•	Loan Against Property (LAP) & Working Capital Loans', 'https://drive.google.com/open?id=115tQewRPJXrjgPfDnOoCG5AgGlNCMfnl', 'https://drive.google.com/open?id=1waUb2AjbQowprBbw6F75zgnI7U4pIxLe', 'https://drive.google.com/open?id=1bK9yhtDfQ0twBGMaUOK4Eldo814PfsAq', NULL, 'Done'),
(13, '2025-10-12 17:55:33', 'Chavda Devendra Naranbhai', 'Owner', 'Chamunda Account service', 'Tax Consultant', '8866508118', 'devendeac04@gmail.com', '5 super Market,Opp. Bus station,Viramgam', 'Viramgam - Ahmedabad', 'Viramgam', 'Viramgam', '1988-06-08', NULL, 'Book keeping , Gst Registration, Return filling and and Income tax return filing', 'https://drive.google.com/open?id=1vYwiKNk0kawwoNRBd8XGIUaueRBsdn-F', 'https://drive.google.com/open?id=10auNV2q-gi4eSvWGhwkAhYV4SL17BeBM', 'https://drive.google.com/open?id=17k4WFEzc8BKMOFW1FGQTjaew7nFO6dyL', NULL, 'Done'),
(14, '2025-10-12 17:57:46', 'JIGNESH JASMUKHLAL JADAV', 'Financial Advisor', 'J J WEALTH CREATORS', NULL, '9825087011', 'jignesh.jadav2017@gmail.com', 'F-105 suryoday 2 near pavapuri bus stop ghatlodiya', 'Ghatlodiya', 'Ahmedabad', 'Viramgam', '1987-01-01', '2012-12-07', 'All Insurance any types of loan mutual fund new car purchase', 'https://drive.google.com/open?id=14BdVEZolSENMLGWzQCxxUTwyBrsBhFsl', 'https://drive.google.com/open?id=1cdhsCCzQO2MRa8WuvcrXQsNM7vUPqubt', 'https://drive.google.com/open?id=1L7rGyqSy0fcvihY-4j83LtruoOCkfJ29', NULL, 'Done'),
(15, '2025-10-13 12:04:23', 'CHAVDA RAVI RASIKBHAI', 'OWNER', 'RAVI COMPUTER', 'IT HARDWARE SALES AND SERVICES', '7990324332', 'ravicomputer3911@gmail.com', '2,3, VISHWAS CITY-1, F F, Maharana Pratap Rd, near 13, Ghatlodiya, Chanakyapuri, Ahmedabad, Gujarat 380061', 'Ahmedabad', 'Ahmedabad', 'Mnadal, Ahmedabad', '1999-04-28', '2025-02-28', 'Ravi Computer — Everything in Computer World

Ravi Computer is a trusted IT hardware and service provider based in Ahmedabad, offering complete technology solutions under one roof.

We specialize in:
💻 Computer & Laptop Sales and Repairs
🔧 Chip-level Motherboard Repair & Servicing
📷 CCTV Camera Supply and Installation
🌐 Networking & IT Infrastructure Setup
🖨️ Printer and Biometric Machine Services
💽 Data Recovery and Software Installation
🧠 Annual Maintenance Contracts (AMC) for Computers, CCTV, and Networking

With a strong presence across the city, we operate from four branches in Ahmedabad:
1️⃣ Ghatlodia (Head Office)
2️⃣ Prahladnagar
3️⃣ Bopal
4️⃣ Naroda

Our team of expert technicians ensures fast, reliable, and affordable IT services with a focus on customer satisfaction and long-term support.', 'https://drive.google.com/open?id=1lfO3ASTLMYdYWdpH_jq7yuAAKuP5aajr', 'https://drive.google.com/open?id=16eeIKQV7ECoXKl3NuuGhjozipo17-Vk4', 'https://drive.google.com/open?id=1tKb2A4zru2lEBArJSMq6wN4KCgmSl3c8', NULL, 'Done'),
(16, '2025-10-13 14:58:26', 'Harshad Rathod', 'Co-founder & Director', 'Accretion Pharmaceuticals Limited & Accretion Nutraveda Limited', 'Healthcare (Pharmaceuticals Manufucturing )', '9723755277', 'harshad11j@gmail.com', '26-31 Xcelon Industrial Park- 1 , B/H intas Pharmaceuticals , Vasna-chacharvadi, Ta: Sanand , Dist: Ahmedabad 382213', 'Sanand', 'Ahmedabad', 'Dhandhuka', '1986-06-11', '2011-12-06', 'From a spark of curiosity to a legacy of innovation—my journey in healthcare began with a simple belief: medicine has the power to transform lives.

I remember the thrill of discovering how a well-formulated drug could change a patient’s life, and that passion propelled me through my academic journey—earning a Bachelor of Pharmacy from LJ Institute of Pharmacy and later an MBA from Madhyanchal Professional University, Bhopal. These experiences laid the foundation for a career spanning over 14 years in the healthcare industry, where every challenge became an opportunity to innovate and lead.

In 2012, driven by a desire to revolutionize healthcare, I became one of the founding members of Accretion Pharmaceuticals, paving the way for innovation and excellence in the pharmaceutical industry. What started as a vision to deliver international-quality healthcare products has evolved into a thriving enterprise, dedicated to excellence and precision. Our early days were marked by bold initiatives and groundbreaking ideas, setting the stage for the transformative work we do today.

The journey didn’t stop there. In 2019, we expanded our horizons with the launch of Accretion INC, forging domestic collaborations that allowed our innovations to thrive across the country. Then, in March 2021, I ventured into the nutraceutical and wellness arena with Accretion Nutraveda Private Limited, diversifying our portfolio and reinforcing our commitment to holistic health solutions.

Today, I lead a passionate team in driving strategic financial management, operational efficiency, and business development. I oversee every facet of our operations—from meticulous financial planning and robust budgeting to ensuring our production processes and quality controls exceed global standards. Every decision, every process, is a step toward our goal of becoming a global leader in healthcare.

My approach to leadership is simple: inspire, collaborate, and empower. At Accretion, we believe in nurturing talent and fostering a culture where innovation thrives and every breakthrough makes a real impact on lives around the world.', 'https://drive.google.com/open?id=12rXTnASCHcAMu0VWud7SV3OV44SdEL9J', 'https://drive.google.com/open?id=1K6VA4462bZJOZg7mQng4dB0SFge4-OmF', 'https://drive.google.com/open?id=1uqFldy4B8zdAY8HHaSPvZH5NA4Uu5lhe', NULL, 'Done'),
(17, '2025-10-14 07:49:40', 'Bhavesh Mori Chauhan', 'Partner', 'Bluegreenfarms', 'Algae, Phytoextracts Wholesale, Trader.', '7359789249', 'bluegreenfarms9@gmail.com', 'shop number 4 bluegreenfarms swagat city swagat city mall-2 adalaj gujarat', 'Adalaj', 'Gandhinagar', 'Surendranagar', '2000-06-04', NULL, 'Bluegreenfarms Working as a Alage based products (Phycocyanin Pigment, Astaxanthin Powder, Spirulina Powder, Zeaxanthin Powder) wholesaler and Exporter.', 'https://drive.google.com/open?id=1A_5eOqk6su-TtDcL5oUwANZHozlQ2ozK', 'https://drive.google.com/open?id=1aSIZ8ktDr-wxU0xvAI146Hg_0epnzZLp', 'https://drive.google.com/open?id=1p9mvyrD8P22bUSIHV1q6zHbgV938_Hnf', NULL, 'Done'),
(18, '2025-10-17 11:39:07', 'Nikita parmar', 'Owner', 'Infowise Digital Solutions', 'IT', '9925228727', 'Satvaraniki@gmail.com', 'B - 803, saaga residency, behind Nirma University', 'Vaishnodevi', 'Ahmedabad', 'Ahmedabad', '1991-08-17', NULL, 'Digital marketing is the promotion of products, service or brands using online platforms and digital channels such as search engine, social media, email, website and mobile apps.', 'https://drive.google.com/open?id=18lnmw7zwprk2nKHM0XlZPp0cxDy0lQnc', 'https://drive.google.com/open?id=16u2oRw9fXGtWJPgLQxOLfpfAfP7m12fH', 'https://drive.google.com/open?id=1daSHfibLBazJ096JOfpzyXlRHSfQ6eV-', NULL, 'Done'),
(19, '2025-10-17 22:41:06', 'KRUPAL BHARATBHAI KADIYA', 'OWNER', 'NAMASTHETU PROFESIONAL SERVICES', 'ACCOUNTING, AUDITING & TAX SERVICES', '9426136949', 'namasthetu.services@gmail.com', 'C-105, SURYAM AURA, NR. MUKTIDHAM ESTATE, JIVANWADI, NIKOL, AHMEDABAD - 382350.', 'NIKOL', 'AHMEDABAD', 'AHMEDABAD', '1998-01-10', NULL, 'Welcome to Namasthetu Professional Services,

We offer comprehensive accounting and taxation solutions tailored to the unique needs of individuals, small businesses, and corporate clients. With a strong focus on accuracy, compliance, and strategic financial planning, we empower our clients to achieve long-term financial stability and sustainable growth.

Our core services include:
•	Bookkeeping Services
•	Financial Statement Preparation
•	Accounting System Setup & Support
•	Income Tax Return Filing
•	Goods and Services Tax (GST) Compliance
•	Tax Deducted at Source (TDS) Compliance
•	Tax Audit & Statutory Audit
•	Human Resource (HR) Services
•	Tax Planning & Advisory
•	Certification Services

Backed by deep industry expertise and a commitment to ethical standards, we collaborate closely with our clients to streamline financial operations and ensure timely compliance with all tax obligations. At Namasthetu Professional Services, “we are more than accountants — we are your trusted financial partners in success.”', 'https://drive.google.com/open?id=11_ylYE-fkOQlqxG-k0cosgzt7w9XVw7g', 'https://drive.google.com/open?id=10FAIdiiC9MnwpGEm0buw2PdrD9ObL_R1', 'https://drive.google.com/open?id=1hFBzL-ykt7NIhJsml-FLzrJWrnb2Kdof', NULL, 'Done'),
(20, '2025-10-20 12:06:45', 'Yash Govindbhai Kadiya', 'Co-Founder', 'Craftic Solutions', 'IT and Software', '9033353762', NULL, 'Remote', 'Nana Chiloda', 'Ahmedabad', NULL, '2000-01-03', NULL, 'We at Craftic Solution build a powerful, scalable, cost-effective and innovative tech products. Specialised in Agentic AI, Mobile Apps, Web and GIS domain. Also cater to customised requirements.', 'https://drive.google.com/open?id=1C34muJxEQ53DnMps9hanIF6b1YYTDHr9', 'https://drive.google.com/open?id=1X3sOUVoUaPyW8sr2jm6NOXgz_XhGZUuP', 'https://drive.google.com/open?id=1-jimDomY_rqjedUN1b6Wy9ux1PfRIB0v', NULL, 'Done (Profile Picture Pending)'),
(21, '2025-11-01 18:11:22', 'Jadav yogesh laxmanbhai', 'Owner', 'Krishna construction', 'Civil work Building contractors', '9725502279', 'yljadav@gmail.com', '16 Sonal nagar part 2 chandlodiya ahmedabad', '16 Sonal nagar part 2 chandlodiya ahmedabad', 'Ahmedabad', 'Morbi', '1980-11-09', '2004-01-26', 'New Building contractors', 'https://drive.google.com/open?id=1L3tOqWrC6mbb7AvMopwLu6tW0d1fG3ZI', 'https://drive.google.com/open?id=1GlTP3fg7RjFJcnXPbVr3uKQgQqBcPyzt', 'https://drive.google.com/open?id=1aUZlYprAGs--z5zZpTMCvqKUnu89HbX_', NULL, 'Done (Logo Pending)'),
(22, '2025-11-01 18:36:36', 'ANAND AMRUTLAL RATHOD', 'OWNER', 'PRUTHVI COMPUTE', 'IT', '9824488101', 'ANAND.98244@GMAIL.COM', '123, AMC COMPLEX, VIRAT NAGAR CROSS ROAD, ODHAV, AHMEDABAD', 'Virat Nagar cross road,', 'AHMEDABAD', 'SURENDRANAGAR', '1976-08-16', '2000-04-24', 'Wholesale Dealing In Computer Parts, Peripheral, CCTV CAMERA, LAPTOP, ALL-IN-ONE, PRINTER, NETWORKING PRODUCT, ATTENDANCE MACHINE, DOOR BELL VIDEO SYSTEM 

REPAIRING HUB OF COMPUTER, PRINTER, LAPTOP, AIO, MOTHERBOARD', 'https://drive.google.com/open?id=1U7Ae-lHn3eP-S86s7RZgQ2KF4QBWXf21', 'https://drive.google.com/open?id=1TIBoyExMHkDC8BV6NLBt4pBwYjjwoP_I', 'https://drive.google.com/open?id=1qi8CTThzsIyIM4odaJi_rssHnK77cqXm', NULL, 'Done (Logo Pending)'),
(23, '2025-11-02 13:40:55', 'SANJAY SAMJIBHAI DALWADI', 'Owner', 'SAI KRUPA TRADERS', 'BUILDING MATERIAL, TOOLS AND HARDWARE', '6353448168', 'dalwadisanjay@gmail.com', '22. Shiv shopping center, Near avasar party plot. Airport road, Hansol, Ahmedabad Hansol. Ai', '22, Shiv shopping center, Hansol', 'Ahmedabad', 'Ahmedabad', '1984-03-03', '2009-02-13', 'Tile Adhesive, Epoxy and Building Materials', 'https://drive.google.com/open?id=1BRZfZjbXIOLbyDZa3rZnY6EpGJvw56MQ', 'https://drive.google.com/open?id=1d2rOG1Lh40rW4cgxUwW6BO5-TlOnhKoq', 'https://drive.google.com/open?id=1YlbzO99lv01Dw8pjoVV9FqUmcl0e2pFF', NULL, 'Done (Profile Picture & Logo Pending)'),
(24, '2025-11-06 11:28:34', 'Bhargav Dilipbhai Jambukiya', 'Founder', 'Stellar Code System', 'IT', '8866562003', 'jambukiya.bhargav26@gmail.com', '909 shivalik shilp', 'Iskcon Cross Road, SG Hwy', 'Ahmedabad', 'Dhandhuka', '1992-11-17', '2019-02-10', 'Stellar Code Systems designs and builds modern digital products for web, mobile, and cloud. Our teams blend deep engineering with thoughtful UX to deliver reliable software, actionable data, and measurable results. From greenfield development to legacy modernization, we bring DevOps discipline, strong security practices, and transparent delivery. Industries we serve include fintech, healthcare, retail, and SaaS.', 'https://drive.google.com/open?id=1jdqHWhGoxfghgy3K1Bre28mGSXHD9iCC', 'https://drive.google.com/open?id=1Gbcw_YM-Xq76nNcAlgHhefhGIrQ7wA7c', 'https://drive.google.com/open?id=1csFPx9fj6d1M_n7ZkElGnadnYp5YmJ7q', NULL, 'Done'),
(25, '2025-11-06 12:21:00', 'PIYUSH SURYAKANTBHAI KADIA', 'PARTNER', 'OM MEDICAL AGENCY', 'Healthcare', '9824604050', 'piyushkadia@gmail.com', 'Plot No. 294, Sector - 23, Gandhinagar.', 'https://maps.app.goo.gl/KJB472ZznMVCFbzk8', 'Gandhinagar', 'Dhandhuka', '1980-12-30', '2005-02-16', 'Retail & Wholesale supplier of Medicines', 'https://drive.google.com/open?id=1OU5R6TTpkj-w-nzURHF9xSgIlNxEHTRR', 'https://drive.google.com/open?id=14XvdiydxQPD5rQcwB7UC2eXjptd78nKe', 'https://drive.google.com/open?id=1GoOkI2slcMWy47Xw3aeNIGPCT0SnfmCL', NULL, 'Done (Logo Pending)'),
(26, '2025-11-06 15:15:33', 'Mitesh Makwana Kalyanbhai', 'Manufacturing Engineering Works', 'Shakti Engineering Works', 'Mechanical engineering', '9904801455', 'miteshmakwana1111@gmail.com', 'A/28 Rameshwar Estate Nr Virat Nagar Canal Road odhav Ahmedabad', 'Odhav', 'Ahmedabad', 'Dhandhuka', '1996-01-10', '2025-02-12', 'Injection Molding Dai Mould Specialist', 'https://drive.google.com/open?id=1qh5Z11lxHxCmG0gKkVkYGdkp6q_MYwF2', 'https://drive.google.com/open?id=1K-jGndclFzLIaipgZRjITRI7sr3aVFP1', 'https://drive.google.com/open?id=1gUBvPSLYRtL4dMnaGqEhQHOA-blMDHA-', NULL, 'Done (Logo & Profile Picture Pending)'),
(27, '2025-11-10 12:18:51', 'Hitesh Pravinbhai Jadav', 'Owner', 'Vihaan Soft Solutions', 'IT', '9924934246', 'jadavhiteshp@gmail.com', 'F-701, Gopinath Pride, Parshwanath Township,  Nr. Bapa sitaram chawk, Nava Naroda, Ahmedabad', 'F-701, Gopinath Pride, Parshwanath Township,  Nr. Bapa sitaram chawk, Nava Naroda, Ahmedabad', 'Ahmedabad', 'Botad', '1991-03-25', '2018-12-10', 'IT Related', 'https://drive.google.com/open?id=13GiQo_VYKEJZBDz6pcq_SyweHhtMuUvo', 'https://drive.google.com/open?id=1Eau6zVDIYGSULzh2GAsOhmlLSY6swb6G', 'https://drive.google.com/open?id=1KGcu30QpBgTjRmyMgCwvOxd25Rsdzcdr', NULL, 'Done'),
(28, '2025-11-14 20:44:55', 'Chintan Pativala', 'Vice President', 'PRACHI GREEN ENERGY PVT LTD', 'Renewal Energy ( SOLAR)', '9106846875', 'prachigreenenergy@gmail.com', 'Gf-1, Shukan Home''s opp Ayodhya Nagari, Aanand Party plot road New Ranip Ahmedabad Gujarat', 'New Ranip Ahmedabad', 'Ahmedabad', 'Patana Bhal', '1993-10-27', '2017-01-22', 'PRACHI GREEN ENERGY PVT LTD found 2020 in mead years, Company working since  last 5 years in all over Gujarat. Prachi Green Energy is simple called Prachi Solar.Prachi Mainly Head office in Ahmedabad and branch office in Botad city location.Company working in Renewable Sector and In Renewable Sector working in Solar field. Government Authorities Empanelment Agency Works like Solar rooftops, Solar Turnkey project and also Ground Mounted Solar. Almost completed 10+ Mw solar  installed in roof top solar and Experience 20+ Mw Ground mounted in I&C work. Prachi  Connected with all over Gujarat 50 plus dealers network. Company future goals work in BES (Battery energy Storage system) and Rooftop Wind Mills .......', 'https://drive.google.com/open?id=1xUptTnzFbZHmJdVhY5qEBytTwIfvTsSd', 'https://drive.google.com/open?id=1eKouDm-fJn99jzlTvKQgWjBjktYqIgXG', 'https://drive.google.com/open?id=1rHMhzN3Lk7j2J7PU7p6AJ28gjNtOh-C9', NULL, 'Done (Photo Pending)'),
(29, '2025-11-21 18:06:14', 'Dharmesh Satwara', 'Director', 'Zybra Private Limited', 'IT', '9909923567', 'dhsatwara@gmail.com', '13th Floor, Gala Empire, Opp. Doordarshan Tower, Thaltej, Ahmedabad - 380054.', 'Thaltej', 'Ahmedabad', 'Ahmedabad', '1992-07-13', NULL, 'Zybra Private Limited is an Indian software company offering cloud-based accounting solutions for Small & Medium Enterprises (SMEs). Their flagship product, named Zybra Accounting Software, is designed to handle everything from GST-compliance and invoicing to inventory and banking, aimed at making business accounting and bookkeeping “effortless, anytime & anywhere”', 'https://drive.google.com/open?id=1BggjPNBuDiqy_d3tFOyY2s2i1wwVCgIz', 'https://drive.google.com/open?id=1wssy7dyXYMrKP2jRaKQEsqrvvG7hxEyD', 'https://drive.google.com/open?id=1CeQKwsSSObhgKSSkSg_I3VX9M7DfrhUj', NULL, 'Done'),
(30, '2025-12-02 17:24:28', 'VISHALBHAI HADIYAL', 'Owner', 'SV GARMENT', 'GARMENT', '8866461190', 'hadiyalvalji@gmail.com', '101 Danev gate-1 nikol gam road Jivanvadi Nikol Ahmedabad', 'Nikol', 'Ahmedabad', 'Botad', '1991-03-07', '2014-02-18', 'We Do jobwork stiching cutting of Indo Western Clothing', 'https://drive.google.com/open?id=1DVRczyXxtnwaTSmkUClO88YA3oJDWjcJ', 'https://drive.google.com/open?id=1yksUtFAlWI0lbh0bfvziRsFFcuRcTHf8', 'https://drive.google.com/open?id=1q3No4KuMrYN3--KLV7_fRZgBGAgWxbCQ', NULL, 'Done'),
(31, '2025-12-08 09:30:23', 'SONAGARA KIRANBHAI DAYARAMBHAI', 'Owner', 'KISHAN HARDWARE', 'Building Materials, Paints, Plumbing, Safety, Industrial Hardware', '7405200705', 'sonagarakd@gmail.com', 'Shop - 2, Gajanan Arcade, Below Green Rio Hotel, Naroda GIDC Road, Naroda', 'Naroda GIDC', 'Ahmedabad', 'Sayla, Surendranagar', '1994-06-01', '2019-01-27', 'We deals in all kind of Building Materials, Paints, Plumbing, Electrical, Industrial Hardware, Safety items(Personal, Road Safety and Fire Safety), Power tools and Hand Tools Wholesale and Retail', 'https://drive.google.com/open?id=1h6qfhGmXmDEyXMDaSi5mW1lEpkHyDc-m', 'https://drive.google.com/open?id=1yUbACTCcxBh5PJP5yHkMVVGpT13I_bXa', 'https://drive.google.com/open?id=1qtNKUJqgBWm63KC8GkRQydwYyjmj1mCw', NULL, 'Done'),
(32, '2025-12-10 10:42:22', 'ASHOKBHAI CHATURBHAI SONAGARA', 'Proprietor', 'KISHAN TRADING COMPANY', 'Construction material suppliers', '9909912371', 'kishantrading307@gmail.com', 'Kishan Trading Company. GF-8, Shyam Shikhar, Opp. HP Petrol Pump, Naroda-Dehgam Road, Naroda-382330 Ahmedabad,', 'https://maps.app.goo.gl/XXCNvLcbekKTXmrr8', 'Naroda, Ahmedabad', 'Sayla', '1978-05-01', '1997-02-15', 'Building material suppliers', 'https://drive.google.com/open?id=1xpiaQZqLMlOIA_Zw1x6b3dvvS16Xdaq0', 'https://drive.google.com/open?id=1ZXWyo0dHXBmoMR2HbF6yZODH5SMLxBW6', 'https://drive.google.com/open?id=1ngpnDMe0ZqOctHHL6BVsdchp97chhbSL', NULL, 'Done'),
(33, '2025-12-20 22:24:11', 'Bhavik Dineshkumar Parmar', 'Founder and owner', 'SHREEJI CAR SPA', 'Automobile', '7383222244', 'shreejicarspa@gmail.com', 'SHOP NO. 1 & 2 GF, SHYAM ELEGANCE, near Rahul Tower Cross road, Satellite, Ahmedabad, Gujarat 380015', 'Satellite', 'Ahmedabad', 'Limbdi', '1991-09-18', '2018-04-25', '"Welcome to SHREEJI CAR SPA, your premier destination for top-tier car care in Ahmedabad, Gujarat! 🚗✨ Specializing in advanced Ceramic Coating and PPF Coating, we offer unparalleled protection for your vehicle’s paint. 

We provide one stop solution for car. Service like, 
 PAINT PROTECTION FILM(PPF)
CERAMIC COATING
CAR WASH 
CAR DETAILING 
CAR SERVICE 
CAR REPAIRING 
DENTING & PAINTING 
CAR ACCESSORIES

SHREEJI CAR SPA guarantees quality and satisfaction. Drive in today and let your car bask in the care it deserves. Protect, enhance, and maintain—join the SHREEJI CAR SPA family now and see the difference! 🌟🛡"', 'https://drive.google.com/open?id=1IZNtkhvH8O9mhBe3LWYR8e_9YwPKHfBf', 'https://drive.google.com/open?id=1lFvlrlkrGcvK2EYgRNOSscXCT8Dx2GJ9', 'https://drive.google.com/open?id=1yWeIAkf2VmZUIoI0-pdyWwaHbZWcQJG3', NULL, 'Done'),
(34, '2025-12-23 20:35:43', 'Jignesh dabhi', 'Owner', 'Helopack', 'Packaging material', '7383096650', 'dabhijignesh1440@gmail.com', 'Behind angat hotel bavla', 'Bavla', 'Bavla', NULL, '2002-12-23', NULL, 'We manufacture all type of packaging material', 'https://drive.google.com/open?id=1Gm1guPZ6S9Kgj0zLb6PhEzxV4-hGLJEq', 'https://drive.google.com/open?id=1FINuzIdst3FLBe6t4BhmWiDHK6jhmb-r', 'https://drive.google.com/open?id=1s_gbiaJkWGFIeK87yYRXKhoMb94VWVL4', NULL, 'Done'),
(35, '2025-12-24 16:32:44', 'JAYDIP BHAI  GHANSHYAMBHAI PARMAR', 'MULTI COLOR OFFSET PRINTING', 'NILKANTH PRINT PACK', 'PRINTING ,', '9624900902', 'NILKANTHPRINTPACK2024@GMAIL.COM', 'JEET COMPLEX , OPP, SHIP BUILDING , NR JAIN TEMPLE, C G ROAD , AHMEDABAD', 'C G ROAD , NAVRANG PURA.', 'AHMEDABAD', 'BARVALA , DI BOTAD', '1991-02-03', NULL, 'ALL TYPE MULTI COLOR PRINTING , BOOK , BROUCHER , DR FILE , CATALOGUE , LIFLET AND ANY PRINTING', 'https://drive.google.com/open?id=1Ut3JnOka6Ubrmd0rK1bVBhIe905gp6QU', 'https://drive.google.com/open?id=183maEkqBws5HO0q8vOtk2i9ttzr9DB75', 'https://drive.google.com/open?id=1lAosKxaFEPWxY40WC6vdSVICx5kL5ODK', NULL, 'Done (Reg. Fees Photo Wrong Uplode)'),
(36, '2026-01-30 23:46:45', 'Dineshbhai govindbhai dalvadi', 'Owner', 'KHUSHI AUTOMOBILE', 'Automobile', '7698290875', 'dineshdalwadi007@gmail.com', 'Shop 08 puspraj apartments', 'Chankyapuri', 'Ahmedabad', 'Mandal', '1996-04-16', '2012-04-16', 'A car workshop (or auto repair shop) is a professional facility providing comprehensive maintenance, diagnostics, and repair services for vehicles. Staffed by skilled technicians, these centers handle tasks ranging from routine oil changes and brake repairs to complex engine diagnostics, electrical system troubleshooting, and bodywork, ensuring vehicles operate safely and efficiently.', 'https://drive.google.com/open?id=1D071a3qjX-lOzoWdpl_G62BCAEe-3CR8', 'https://drive.google.com/open?id=1F6GoXQZBWzfocXxGnGeuDmXcUaYO_dUs', 'https://drive.google.com/open?id=1idGO5u-NskpalsYY_2Vy5gVmO7Prqdpu', NULL, 'Done (Photo, Logo &  PAyment SS Pending)'),
(37, '2026-02-06 19:59:03', 'SANJAY MAKWANA', 'CEO', 'VANDE MATARAM EXPORT', 'IMPORT EXPORT', '9898364041', 'MAKWANASANJAY1909@GMAIL.COM', '112/113 SATVAICON BUILDING. VASTRAL METRO JUNCTIONS SP RING ROAD VASTRAL AHMEDABAD GUJARAT INDIA 382415', '112/113 SATVAICON BUILDING. VASTRAL METRO JUNCTIONS SP RING ROAD VASTRAL AHMEDABAD GUJARAT INDIA 382415', 'AHMEDABAD', NULL, '1986-02-10', '2007-12-05', 'WE ARE IMPORT EXPORT BUSINESS & CONSULTANT, WE PROVIDE BEST KNOWLEDGE IMPORT EXPORT BUSINESS', 'https://drive.google.com/open?id=1iEctZvgsRmi8Vk0MLuTOejz6o1CPthyj', 'https://drive.google.com/open?id=1FV-0XW4PO5znOwCLryo1OTKmbs0xOY88', 'https://drive.google.com/open?id=16sD2GgB6ASH0dtCAY51aXAPcubeZqGDE', NULL, 'Done (Profile Picture Pending)'),
(38, '2026-04-01 17:40:03', 'Dr. Dineshkumar Kantilal Dabhi', 'Critical Care physician', 'Dr. Dabhi’s Divine Health Care', 'Heath Care', '7600555510', 'drdkdabhi@gmail.com', 'Dblock, Ground floor shop no 2, opposite ID Patel School, Ganesh Park Road, Ghatlodia, Ahmedabad', 'Ghatlodia', 'Ahmedabad', 'Ahmedabad', '1981-09-15', '2009-02-22', 'Treatment of each and every acute and chronic disease  and critically ill patients including heart attack, brain hemorrage, brain stroke, Pancreatitis, kidney disease, Dengue, Malariya, Pneumonia, Diabetes, Hypertension, Thyroid dysfunction', 'https://drive.google.com/open?id=1OZsw2P2wfMuXFiTpCPpjDG-fY01w2DtZ', 'https://drive.google.com/open?id=1eqApG55LwGBhSClblrr9_wPyLTJG5y-X', 'https://drive.google.com/open?id=1UwSBX4gEyAhBxdp15VCETyjhGZiFmypU', NULL, 'Done (Profile Picture Pending)'),
(39, '2026-04-01 21:36:56', 'Deepakkumar laljibhai sonagara', 'Proprietor', 'Kishan construction chemicals', 'Construction chemicals', '9978632413', 'Kishantrading307@gmail.com', 'GF08, shyam shikhar complex, Opp HP petrol pump, Naroda-Dehgam Road, Naroda', 'Naroda', 'Ahmedabad', 'Surendranagar', '1990-08-02', '2016-01-30', 'We deal in tile adhesives, block joint mortar, waterproofing chemicals, industrial floorings', 'https://drive.google.com/open?id=15wxeOKrhCgoveMrnAa02kJ7tT6hIqqya', 'https://drive.google.com/open?id=1qlm-8z7PrYBLNNYYDhf16COuriuFu_JT', 'https://drive.google.com/open?id=169BCFCc-FPUcMP10QhV5ql1l3CzlrPq5', NULL, 'Done'),
(40, '2026-04-03 16:51:16', 'Dr Pravin Parmar', 'Founder', '1 Million Entrepreneurs International Forum', 'Community of Collaboration', '9316120831', 'millionentrepreneurs@gmail.com', '805, Sapath-1, Bodakdev, SG Highway', 'Bodakdev', 'Ahmedabad', 'Botad', '1984-12-16', '2009-05-16', 'It all starts with one question…

👉 “How many lives did you impact this month?”

Peers Global is a community of collaboration, where entrepreneurs don’t just network —
they help, connect, and grow together.

Every referral, every connection, every support…

👉 creates impact.

And that’s why…

👉 We are not counting members…
👉 We are counting lives impacted.', 'https://drive.google.com/open?id=1P_nwDy2r115PQqA9y7SjojGFzKKztmKL', 'https://drive.google.com/open?id=1Ygb9VyBU9ICqNkpILrBXeyXG2hw-xw7B', 'https://drive.google.com/open?id=1WAIqsZOqfL7uotSERmrawaiM2EXXm1EB', NULL, 'Done'),
(41, '2026-04-03 21:59:07', 'KANZARIYA KAUSHIK NAGARBHAI', 'Owner', 'BHKG GROUP', 'Air Conditioner Sales & Service', '7405701518', 'kaushikkanzariya999@gmail.com', '3, Siddhivinayak Soc. Part-2, Chankiyapuri, Ghatlodiya', 'Ghatlodiya', 'Ahmedabad', 'Dudhai', '1996-10-03', NULL, 'Sales & Service of Air Conditioner of all Company On reasonable price.', 'https://drive.google.com/open?id=1KhisgRPiinbSYhryNLZMxsPr_YSO5qFR', 'https://drive.google.com/open?id=1Bj59QabrHmuiWPCuZV3VJtn_mnOxqZPe', 'https://drive.google.com/open?id=1oiTBIw7RHuwFVcvRsc-EQGhkaGtdk6Ss', NULL, 'Done (Profile Photo Pending)'),
(42, '2026-04-04 14:43:56', 'Bhavdeep Keshavlal Nakum', 'Director', 'STELLARADE ENGINEERING PVT LTD', 'AEROSPACE, DEFENCE AND ENERGY', '9033959794', 'BHAVDEEP.NAKUM@STELLARADE.COM', 'B-1204, SHILP ANANTA, OPP. CLUB O7, SHELA, AHMEDABAD', 'SHELA, AHMEDABAD', 'AHMEDABAD', 'At Post: SHIVA, Taluka: Bhanvad, Dist: Devbhumi Dwarka', '1991-11-11', '2019-02-21', 'Stellarade Engineering Pvt. Ltd. serves in the aerospace, defence, and energy sectors, providing end-to-end technical and programmatic support. The company’s services include product development, project development, project management, and strategic business advisory, tailored to the requirements of government agencies, defence organisations, and private sector stakeholders.', 'https://drive.google.com/open?id=1lV5fmoc7cXuyG5AHe0kWJK-5zt4tGtAn', 'https://drive.google.com/open?id=1jgplvqNjzww9gGkTu-GsrPbLjB3b2BNE', 'https://drive.google.com/open?id=153Rk1f2l4YmalbBzVX2OugL4D8EHTkVh', NULL, 'Done'),
(43, '2026-04-06 18:04:48', 'Vijay Chandubhai Kanzariya', 'Gamified event activity', 'The Game Hour', 'Event planner', '9924007700', 'info@thegamehour.com', '4THF-406, Shilp Satved, Beside Sindhu Bhavan Hall, Sindhu Bhavan Road, , Bodakdev, Ahmedabad, India, 380054', 'Sindhubhavan Road Ahmedabad.', 'AHMEDABAD', 'Dhandhuka', '1975-12-18', '1997-02-16', '1. The Game Hour specializes in creating engaging and interactive gaming experiences for all types of events, including corporate gatherings, birthday parties, school events, and community festivals.
2. We offer a wide range of activities, from fun and competitive games to strategy-based and team-building challenges, ensuring entertainment for all age groups.
3. Our expert facilitators bring energy and excitement to every event, making sure participants have an unforgettable experience filled with joy and laughter.
4. We provide customized game setups, including themed activities, indoor and outdoor games, and large-group engagement sessions tailored to client preferences.
5. With a mission to promote fun, teamwork, and active participation, The Game Hour is your go-to partner for turning any occasion into a thrilling and memorable celebration!.', 'https://drive.google.com/open?id=1RKaKNsu7wuuvdldw_Ush_GobcABBf9kt', 'https://drive.google.com/open?id=1JctQzsNVpLB9EjZDxlW30ytst0Yx62uN', 'https://drive.google.com/open?id=1ie1KhDwKikehuEtKY_mVJ-ryRkc3DJM8', NULL, 'Done'),
(44, '2026-04-06 22:47:02', 'Khandla Prahladbhai Savji bhai', 'Owner', 'Parishram', 'Construction and power tools', '9898885537', 'Info@parishramindia.com', 'Ground floor no-17 sundram aarket science city', 'Science city sola', 'Ahmedabad', 'Surendrnagr', '1981-09-06', '2007-05-27', 'Civil contraction', 'https://drive.google.com/open?id=17fw9d-7ViFNi4q8tNn8-1le67otzuy0V', 'https://drive.google.com/open?id=1nOTCfe0KpJ2-oVceoxOGrDbIVI2uV06n', 'https://drive.google.com/open?id=1KX9VbTlb5lCL7ufa9JpqN16KEVYKjdZF', NULL, 'Done'),
(45, '2026-04-13 16:49:12', 'MITULKUMAR JAGDISHBHAI KANJARIYA', 'OWNER', 'M J KANJARIYA & CO.', 'CHARTERED ACCOUNTANTS', '9737662121', 'mitul242.mk@gmail.com', 'E-408, GANESH GLORY-11, NEAR BSNL OFFICE, S G HIGHWAY, JAGATPUR, AHMEDABAD-382470', 'JAGATPUR, S G HIGHWAY', 'AHMEDABAD', 'BHAVNAGAR', '1992-10-21', '2023-01-28', 'INCOME TAX RETURNS, GST REGISTRATION AND RETURNS, ACCOUNTING, AUDIT, TRUST WORK, COMPANY / LLP / PARTNERSHIP FIRM INCORPORATION, RERA, ETC.', 'https://drive.google.com/open?id=1pUXrBitH3QsyCeF9u0IA_7XlLG5FHobK', 'https://drive.google.com/open?id=1Cq1lsQYTAGVf6TOpcEt3AP1cVWEVwmdT', 'https://drive.google.com/open?id=1edzIrPROOENIl4k1SzGLGjvOihYy-dLm', NULL, 'Done'),
(46, '2026-05-01 21:32:10', 'Parth sonagara', 'Proprietor', 'Prime tools industries', 'Hardware and Power tools', '9727686449', NULL, 'GF-8, shyam Shikhar, naroda-dehgam road, new naroda, ahmedabad', 'Naroda', 'Ahmedabad', NULL, '2001-06-02', '2023-03-09', 'We have our own brand in power tools industries named PRIME', 'https://drive.google.com/open?id=1Wgs-IEpufv-ue4yzPCXeBXfgpX-GowaZ', 'https://drive.google.com/open?id=1iwirOci2fo-_ckvOQrA3utpJOy2dK6bR', 'https://drive.google.com/open?id=1mkPdaprOhvpn98niG0nT-k8K8nqitxJX', NULL, 'Done'),
(47, '2026-05-02 19:48:58', 'Alpesh Parshottambhai Sathwara', 'Financial Advisor', 'AS Wealth Solutions', 'FInancial Service', '9924938288', 'alpeshsathwara77@gmail.com', '326, Arth Business Centre, Nikol SP Ring Road, Ahmedabad - 382350', 'Nikol Ring Road', 'Ahmedabad', NULL, '1995-05-27', '2021-02-28', 'I am providing All types Investment Services and Recruit Financial Advisor
Life Insurance
Health Insurance
Motor Insurance
Mutual Fund
Demat A/c
FD, BOND, NCD
and I also offer to individual who ready for his career start in Financial Advising.', 'https://drive.google.com/open?id=1XDXRkl8RrVa4JKe92Jv8dzl9bjiFyIpE', 'https://drive.google.com/open?id=1Dqq_CNQVF5GK0lo_QYwYNIEFqVXXS5_a', 'https://drive.google.com/open?id=1R6aGulyffkjb6H6yNNCfDQsyNC7MGv1F', NULL, 'Done'),
(48, '2026-05-03 07:17:25', 'KANTIBHAI KANJIBHAI Dabhi', 'Owner', 'Helmik Enterprises', 'Hardware Tools', '8866437143', 'helmikenterprise1@gmail.com', '48 Devgram Parisar industrial park  Kathwada Singarva Road, Nr. Vivan industrial park,', 'Kathwada', 'Ahmedabad', 'Ahmedabad', '1996-10-08', '2019-01-01', 'Wholesale in Tile Tools, Wooden Tools, agricultural Tools', 'https://drive.google.com/open?id=1UECuLkTxWjIDtv7_TraVM9uc4BzHPi6Y', 'https://drive.google.com/open?id=1NNe_BPObS_uYcb-ftmV9gqibiMJp0gso', 'https://drive.google.com/open?id=1sMujp2Vwo1Yzg5DQ49toV62f9RYZ-9Ju', NULL, 'Done'),
(49, '2026-05-03 18:44:25', 'Dr Nikita Kanzariya', 'Owner', 'Lavanya Multispeciality Dental Clinic', 'Healthcare', '9737673352', 'drnikita151193@gmail.com', '4-5, 1st floor l, Sunrise Avenue, Opp Vedant Hospital, Stadium to commerce college road,', 'Navrangpura', 'Ahmedabad', NULL, '1993-11-15', NULL, 'Lavanya Multispeciality Dental Clinic is a modern, patient-centric dental care center committed to delivering comprehensive and high-quality oral healthcare.', 'https://drive.google.com/open?id=1KpjVKBA9ceOZlSSolmbb_RB-jcDci_eZ', 'https://drive.google.com/open?id=1ebCnKPYGoZBcr65kjj40F5G_Jn3ip2A3', 'https://drive.google.com/open?id=1SwEyhZO69O5FBQZpNzYCcxXESwzZGQlk', NULL, 'Done'),
(50, '2026-05-05 19:39:46', 'Parag amrutlal sonagra', 'Bussines head', 'Hom pharma', 'Pharmaceutical, medicine', '9825528269', 'hompharma22@gmail.com', '91 suminpark, nr.water canal vastral Ahmedabad', 'Vastral', 'Ahmedabad', 'Upleta', '1977-07-22', '2002-02-22', 'Mfg of medicines, and sale and marketing of medicine', 'https://drive.google.com/open?id=1_f6IPfUcQpzdJydlGFwqI7Fm4XTmYbA9', 'https://drive.google.com/open?id=13gdfVUx6l6bh_k_6gXcpP3bq7BnHwtUa', 'https://drive.google.com/open?id=19yJ7BZjeUPkPo9eOtXjgQS5Qw7x2jZW9', NULL, 'Done'),
(51, '2026-05-09 20:00:02', 'Pradip Prabhubhai Sathwara', 'Managing Director', 'Rama Realty', 'Real estate Firm', '6352867546', 'pradip13.pd@gmail.com', 'Bhuyangdev char rasta Elite Magnum', 'Bhuyangdev Narayanpura', 'Ahemdabad', 'Botad', '1997-09-04', '2024-11-17', 'Managing Brokerage firm', 'https://drive.google.com/open?id=1uCYXrv4AdCxycnv7z98j-qeJwWVrMa2q', 'https://drive.google.com/open?id=1_mHaYZOWsaEmKpq8TYZbOg8kriLQmoCT', 'https://drive.google.com/open?id=1Jp17CuvDpIZ99HwpBN6WXMVfiEUAX2K_', NULL, 'Done'),
(52, '2026-05-09 22:35:12', 'Chandresh mori', 'Machine', 'JK power tools', 'Tools & machinery', '7600697734', 'morichandr@gmail.com', 'Gota circle opposite Ambika dalwada', 'Gota circle', 'Ahmedabad', 'Surendranagar', '2001-08-07', NULL, 'Machine service', 'https://drive.google.com/open?id=1FogB4pqMmVOyu_or7rFcBQlzYa_hhmRR', 'https://drive.google.com/open?id=11xKbX1GnB7KRElikfL8B8u6rhwk61j0e', 'https://drive.google.com/open?id=1YRiAu_E22sR33lqKTjLwG0U9khkO2aYN', NULL, 'Done'),
(53, '2026-05-10 12:25:26', 'Khandla paresh govindbhai', 'Owner', 'JK PG HOMES', 'Boys pg', '7874850515', 'Khandlaparesh9@gmail.com', '2, shivshakti nagar, damru circle, maharana pratap road, Chanakyapuri, ahmedabad, 380061', '2, shivshakti nagar, damru circle, maharana pratap road, Chanakyapuri, ahmedabad, 380061', 'Ahemdabad', 'Wadhwan', '2002-03-28', NULL, '"JK PG Homes: Where Comfort Meets Convenience."

Dedicated to providing premium co-living spaces in Ahmedabad, JK PG Homes is the ideal choice for ambitious students and professionals. We prioritize your well-being with top-tier hygiene standards, 24/7 utilities, and a peaceful ambiance. Focus on your career and studies while we provide the warmth and security of a home.', 'https://drive.google.com/open?id=1QERi9SROY_LlmqiYb1cIED4WU5_dU9tt', 'https://drive.google.com/open?id=1xHdcwSWOPrLPJA3wLDBQcjRHItZ59XYp', 'https://drive.google.com/open?id=13fyJF2zZ99V6UdcXVpVe8e5hcdD2Y5Rw', NULL, 'Done'),
(54, '2026-05-10 21:14:35', 'Chandresh M Kadia', 'Proprietor', 'VIDHI INDUSTRIES', 'Mfg:Hotel Kitchen Equipments', '9426079401', 'vidhiindustries2007@gmail.com', 'S/17,Siddhi Vinayak Estste, New Cotton Mill Char Rasta, Amraiwadi, Ahmedabad', 'Amraiwadi', 'Ahmedabad', 'Ahmedabad', '1976-09-11', '2000-02-10', 'Vidhi Industries Mfg:Hotel Kitchen Equipments', 'https://drive.google.com/open?id=1cm1vRNvU8F30HhPyMilFlTmyAhScHESA', 'https://drive.google.com/open?id=1aAJiSQs_g-So402IL4K376uRqLUV0mNG', 'https://drive.google.com/open?id=1J26bcWEdLeSQHozR8CH-PC7xQ3HKcQoy', NULL, 'Done'),
(55, '2026-05-11 17:30:21', 'Dabhi Dixit Bharatbhai', 'Owner', 'Swagatam Group', 'Construction Developer', '7201804336', 'dixitdabhi.110@gmail.com', 'Hanspura', 'Naroda', 'Ahmedabad', 'Botad', '2001-10-01', '2025-01-17', 'Development of Residential and Commercial projects', 'https://drive.google.com/open?id=17BubdrXqINyszj2GxyL-5xo4hkf2Gndq', 'https://drive.google.com/open?id=1V_-8SG7Y7vIO8UKoNsq3J3kjJwF3Aszq', 'https://drive.google.com/open?id=1tG7Qp04dWCbPo8c0nOT7u8DUJWivcsxF', NULL, 'Done'),
(56, '2026-05-11 17:48:11', 'Jaysukhbhai Dabhi', 'Owner', 'Majestic group', 'Real estate devloper', '7043841578', 'dhruvdabhi947@gmail.com', 'Nr Everest impressa', 'Hanspura', 'Ahmedabad', 'Ahmedabad', '2007-04-09', NULL, 'Devlopment of residential', 'https://drive.google.com/open?id=1lh-2ZUAzzh9ikM36Rn8thdCiafj-u8zR', 'https://drive.google.com/open?id=1wlWGfRNKmNv1fi1qBti-RYlg_rAeJzOQ', 'https://drive.google.com/open?id=1EkzjzJ_d3yC7WhpLNeItXllBAB04FZA7', NULL, 'Done'),
(57, '2026-05-11 18:45:40', 'Mori Harsh Mansukhbhai', 'Marketing And owner patner', 'Express Elevator Infrastructure Private Limited', 'New Lift installation end maintenance', '88688762768200862591', 'moriharsh375@gmail.com', 'Ahemdabad', '601 Aaron Spectra, Beside Rajpath Club, Rajpath Rangoli Road,  Bodakdev, Ahemdabad.', 'Ahemdabad', 'Ta - Halvad (district -Morbi )', '2006-08-22', NULL, 'JAY SIDDHNATH MAHADEV 
MY SELF -  HARSH MORI 
EXPRESS INFRASTRUCTURE PRIVATE LIMITED 
Aa Aamari company che Jo koi reference Hoi to Mane jan karjo  High rise .Bungalow .Commercial. Residency Ma  Lift ni Requirement hoi to contact. Karva vinanti 🤝🙏', 'https://drive.google.com/open?id=1Sh2YxOzxzIe_ZYvAGISjTsaOWcnFJqYj', 'https://drive.google.com/open?id=1ErYxDCgF-SW5EIR5UHUV5cvWuxyEFR4m', 'https://drive.google.com/open?id=1ygc10C57SwK1xHZrt2FaRX5R4j_sTgYL', NULL, 'Done'),
(58, '2026-05-12 10:15:55', 'Sathavara vimalbhai Parsottambhai', 'Owner', 'Shree ChamundaKrupa Build Care', 'Construction Chemicals', '9638021520', 'pamischemical@gmail.com', 'shop no. 29,victory sunrise, gota', 'Gota', 'Ahmedabad', 'Ahmedabad', '1980-07-09', '2004-02-16', 'Pamis is a manufacturer of construction chemicals, offering products like epoxy grout, tile adhesive, and tile grout. The company focuses on providing durable, high-quality, and reliable products for modern construction projects.Company also provides services like labour work for epoxy grout , epoxy flooring.', 'https://drive.google.com/open?id=1a7iZblgwStMI7wZrALwHbT8fCsuvGVGa', 'https://drive.google.com/open?id=1GwadFo9qv_bbeh1kp5VhoGbuWDt7tzQu', 'https://drive.google.com/open?id=1-osWIWaaWcf8mk7ApMNxV6qXm33wjwHh', NULL, 'Done (Profile Picture Pending)'),
(59, '2026-05-12 23:20:41', 'Gaurang Kanzariya', NULL, 'BHKG GROUP Air Conditioner', 'Bhkg group air conditioning split and cassate ac service And cooling solution', '8200326927', 'gaurangkanzariya119@gmail.com', '3, siddhivinayak society vibhag-2, behind marutinandan hotel, chankyapuri, Ghatlodia', 'Ghatlodia', 'Ahemdabad', 'Dudhai', '1995-05-22', '2023-03-12', 'All air conditioner repair and service', 'https://drive.google.com/open?id=1trq76Jf4IfXl9RrnbwTsQ9fMaQl3Kb1_', 'https://drive.google.com/open?id=15mg321WymKT_fgSpbR-pdZjsGgVqmpsb', 'https://drive.google.com/open?id=1-D2qVVa6DL8Q5sVjM6D1Ct3Wvfaqg_UO', NULL, 'Done'),
(60, '2026-05-13 09:22:35', 'Dalwadi jignesh kanubhai', 'OWNER', 'J G Profile Setter & Glass', 'Glass Alliminium', '9512989047', 'Jigneshpakhani2411@gmail.com', 'Chandlodia Shivam Gas Line', 'Chandlodia', 'Ahmedabad', 'Lolada', '1998-11-24', NULL, 'All Type Turf Glass Setter', 'https://drive.google.com/open?id=1tLY9h2if7EhKNKiKs3zcIWYPSp5HJqDb', 'https://drive.google.com/open?id=16YLUY1oWBzo87QEDX5B02r-VEnN7y3Q7', 'https://drive.google.com/open?id=1yE13p_SN7MYxJxM_zsR6Q2OfNuhLsHFH', NULL, 'Done (Logo Pending)'),
(61, '2026-05-13 12:57:26', 'Shailesh Thakarshibhai Sonagara', 'owner', 'KISHAN SAFETY SOLUTIONS', 'IT services and industrial SAFETY equipment', '8128000802', 'sonagara.shailesh 3112@gmail.com', 'Beside UGVCL office, Naroda- dehgam Road, New naroda, Ahmedabad 382330', 'Naroda', 'Ahmedabad', 'Sayla', '1989-12-31', '2016-01-30', 'we work on 2 business 
1. Kishan Safety solutions 
supplier of all types of industrial and construction safety equipments and installation services.

2. Digital SKYLINK
We provide digital marketing and software development services.', 'https://drive.google.com/open?id=1TjGZWUQ3kjS1dSaFpjNhMPlbLkzkmBq6', 'https://drive.google.com/open?id=1UvIC9IH628brL4lTxAfRrSi3uXxW2ySc', 'https://drive.google.com/open?id=16ONDxdqiXkdqqtfscbEczqIDULmTcKTK', NULL, 'Done'),
(62, '2026-05-13 14:22:29', 'Apurva Vijaykumar Kanjaria', 'Founder and CEO', 'E² Global Cyber Security', 'IT/Cyber Security Services', '7779059966', 'apurva@e-squareglobal.com', 'Ahmedabad', 'CTM', 'Ahmedabad', 'Ahmedabad', '1998-12-29', NULL, '🚨 One vulnerability is enough.
Security is no longer optional.

E² Global Cyber Security Solutions
 delivers real-world cybersecurity services designed to identify, validate, and reduce risk before attackers exploit it.

💻 Web & Mobile VAPT
☁️ Cloud Security
🛡️ Compliance & GRC
🎯 Red Teaming
🔍 Risk Assessments
📑 Evidence-Driven Reporting

No fluff. No generic reports.
Just practical security with measurable impact.

📩 Connect with us today
🌐 e-squareglobal.com

#CyberSecurityIndia #VAPTServices #CyberRisk #EthicalHacker #SecurityAudit #SOC #InfosecCommunity #CyberAwareness #DigitalSecurity #NetworkSecurity #OWASP #CyberExperts', 'https://drive.google.com/open?id=1BUDZTiWKFRf9G0wmdDNLh7bRSedPW6zg', 'https://drive.google.com/open?id=1djQeYsichNcFfuaum3EPC1qxLm70Mnxy', 'https://drive.google.com/open?id=1hkzRqhxtiCuOopBvAR_pRg9LDI4bzVLj', 'Ghodasar', 'Done (Reg. Fees Screen Short Pending)'),
(63, '2026-05-13 17:14:40', 'JAYDEEP VIJAYBHAI SONAGARA', 'PROPRIETOR', 'KISHAN MARBLE', 'CONSTRUCTION', '8238117641', 'JDSONAGARA681@GMAIL.COM', 'KISHAN MARBLE,NARODA - DAHEGAM ROAD,OPP.ARSH EMPIRE,NARODA', 'NARODA', 'AHMEDABAD', 'SAYLA,SURENDRANAGAR', '2001-01-25', '2024-12-14', 'DEALS IN GRANITE,MARBLE AND BUILDING MATERIALS', 'https://drive.google.com/open?id=1XuaxHYIC2ihVZkImXZAUTJzlLGLbIZas', 'https://drive.google.com/open?id=1DElJU2c-hpvp6mQ8hbPBkc0D1on-pcq7', 'https://drive.google.com/open?id=1vzBgpvJF5W1hnyPdEaRMLwvZiU3ZJcnp', 'NARODA', 'Done'),
(64, '2026-05-14 16:06:48', 'HADIYAL VIJAY', 'Sathwara Brother kitchen , Toys and bath accessories owner', 'Sathwara brother''s', 'Kitchen, Toys and bath accessories', '9624348997', 'vijayhadiyal1993@gmail.com', '4th floor 417 Hilltowen landmark near Das khaman nikol naroda road Ahmedabad', 'https://maps.app.goo.gl/CbU83eFjdDKaJSWz5?g_st=awb', 'Ahmedabad', 'Botad', '1993-08-07', '2013-02-02', 'Wholesale and E-commerce', 'https://drive.google.com/open?id=1Ug0Jt2cEE7fEUdPuuxQ41G9Y-OvOd-Gx', 'https://drive.google.com/open?id=10Rs32BLdmnOuYncI6v5EZKJrHk3yGl7U', 'https://drive.google.com/open?id=1rik1uaHDUmLBcPAP38wX5wv_g6JeeTXH', '4 Shiromani tenamen nr viratnagar canel road odhav Ahmedabad 382415', 'Done'),
(65, '2026-05-15 12:42:15', 'Chirag Govindbhai Parmar', 'Proprietor', 'Dheyey Consultancy', 'Tax Consultancy Service', '9924246408', 'chiragsatwara1@gmai.com', 'First Flour, Apurvam B Desai, Nr.Vandematram Circle, Vandematarm Gota', 'First Flour, Apurvam B Desai, Nr.Vandematram Circle, Vandematarm Gota', 'Ahmedabad', 'Bhavnagar', '1978-02-11', '2003-01-23', 'Dheyey Consultancy is a professional proprietorship firm specializing in taxation, accounting, bookkeeping, direct and indirect tax compliance, and financial advisory services. We offer comprehensive support to individuals, MSMEs, and corporate clients, including management of government tax compliances, departmental notices, assessments, and preparation of replies to statutory authorities. Our focus is on delivering accurate, timely, and cost-effective tax and accounting solutions that enable businesses to maintain compliance, streamline financial operations, and achieve sustainable growth', 'https://drive.google.com/open?id=1_lt1LYJQUq3TxuqX2Dob1xdbWwLcWPU-', 'https://drive.google.com/open?id=1WDC7FxCj9YnMPutZegSdmqt6Z2UbxoZo', 'https://drive.google.com/open?id=1U2vEHVu2zy4OBFZaZAV2Jhipal9PcE2B', '504, Bhimnath Aparment, Nr. New CG Road Chandkheda', 'Done (Profile Picture Pending)'),
(66, '2026-05-15 16:31:12', 'Vishal Parmar', 'Co-Founder', 'Peers Global Business Media Pvt. Ltd.', 'Community', '7041151714', 'hello.vishalparmar@gmail.com', 'building, 805 shapath 1 opp rajpath club gordhan thal, Sarkhej - Gandhinagar Hwy, Ahmedabad, Gujarat 380015', 'S. G. Highway - Pakwan cross road', 'Ahmedabad', 'Botad', '2002-01-25', '2026-02-20', 'Peers Global is a dynamic business networking and growth platform that connects entrepreneurs, startups, business leaders, and professionals to create meaningful collaborations and growth opportunities. Through curated networking meetups, leadership circles, business events, workshops, and industry-focused communities, Peers Global aims to empower entrepreneurs with the right connections, visibility, and business support.

The platform is dedicated to building a strong entrepreneurial ecosystem by encouraging knowledge sharing, partnerships, and community-driven growth across India.', 'https://drive.google.com/open?id=1kw7m2EzXE26WpsNvg810H5heIJhF7N8W', 'https://drive.google.com/open?id=1Eesp-ZYZLJOI6Yvfr-mxGP3NIC2KMyf0', 'https://drive.google.com/open?id=1ITi9N6vlvssqu2HQ-PK-hTDoyYxEe24R', 'Godharej Garden City', 'Done (Membership Payment Attachment Wrong)'),
(67, '2026-05-16 14:13:51', 'Haresh Laxmanbhai Parmar', 'Advocate', 'Advocate', 'Legal', '9925470100', 'hareshadvocate@yahoo.co.in', 'Grahak Bhavan, Gota, Ahmedabad', 'Gota, Ahmedabad', 'Ahmedabad', 'Dhandhuka', '1978-07-05', '2005-02-11', 'Practicing in Consumer Court as an Advocate', 'https://drive.google.com/open?id=1tj7O7_uJ3y9hUOsr0os5C0dW3Fuh8tEu', 'https://drive.google.com/open?id=1irocZIhvKvFjBZfzDhkfl7HpUJN5wO04', 'https://drive.google.com/open?id=1DEZyn4cDxmPtQhqNhfRs80VQILMsT1YO', 'Gota, Ahmedabad', 'Done'),
(68, '2026-05-16 19:44:15', 'RAVINDRAKUMAR JASMATBHAI CHAVDA', 'PROPRITOR', 'SHIVSHAKTI INDUSTRIES', 'S.S.UTENSILES MANUFACTURING', '9426579847', 'rjchavda11@gmail.com', 'C/10 G.I.D.C ROAD NO 3, ON NTINOL TANK ROAD, AMBICNAGAR, ODHAV. AHMEDABAD', 'ODHAV, AHMEDABAD', 'AHMEDABAD', 'DHANDHUKA', '1978-08-11', '2004-05-10', 'S.S.UNESILES MANUFACTURING', 'https://drive.google.com/open?id=1C06YMPvbJhq_pUUxFao7Ha8NeA7p_Ton', 'https://drive.google.com/open?id=1j9Fr1Tx1_NXZ3GrYEJh-IbAHPG0D7SsC', 'https://drive.google.com/open?id=1rw5_gyouSx94SXNchzCnhoFK-0rY_2cD', '48 PATHIK BUNGLOWS, B/H MUKTIDHAM ESTATE, JIVNWADI ROAD, ON 80 FEET ROAD, NIKOL, AHMEDABAD', 'Done'),
(69, '2026-05-21 23:08:56', 'Nilesh Ramanlal Chauhan', 'Gynecologist', 'Sukrut Hospital', 'Hospital Laboratory Operation Sonography', '9825098321', 'sukruthospital@gmail.com', 'Sukrut Hospital, 304  Shoppers Plaza, Adani Shantigram', 'https://share.google/7ixgOgRaatdhSdED1', 'Ahmedabad', 'Botad', '1978-06-18', NULL, 'https://sites.google.com/view/sukruthospital/home', 'https://drive.google.com/open?id=1j24OnjUL592Uv5nebFGBMTQzc5aOB6QK', 'https://drive.google.com/open?id=1yrp4SQIvInghNJfr5Zrxl9ZwG_yZOSiD', 'https://drive.google.com/open?id=1j6Nhvwd14uYmwBJItE44EGWpF4cHrDp9', 'B4 1101 Waterlily Adani Shantigram https://goo.gl/maps/sHgQJfVuxQhB4uZX6', 'Done'),
(70, '2026-05-28 10:49:31', 'Chirag Jivanbhai Kanjariya', NULL, 'WEBINTOTO', 'IT Company', '9825409350', 'chirag@webintoto.com', '605, Pushti Heights, Gurukul Rd, Nilmani Society, Memnagar, Ahmedabad, Gujarat 380052', NULL, NULL, NULL, '1989-07-24', NULL, NULL, 'https://drive.google.com/open?id=17esnlK9T0Qv07cZau93dxqoEjmmoABSz', 'https://drive.google.com/open?id=1gAkdc-EqWEDkhUrY9V6b1A67XN0W1B6B', 'https://drive.google.com/open?id=1_E_sn05DyS-ZSfTgClzwvqwO0yc4g2Rg', '201, Amilaxmi Apartment, Lad society road, Vastrapur, Ahmedabad', 'Done'),
(71, '2026-05-30 17:39:55', 'Sathvara mitesh nitinbhai', NULL, 'Electrical contractors', 'Construction', '9377669267', 'mitesh17586@gmail.com', '9 amarnath industrial park nr maize product singarwa kathwada Ahmedabad', NULL, NULL, NULL, '1986-05-17', NULL, NULL, 'https://drive.google.com/open?id=1hj4H_iIM1TLtO_VY4WjiU_lF-vYgZXNG', 'https://drive.google.com/open?id=1qeI8IApN5xyqD7QYTGPAWHya-Ka2uVjj', 'https://drive.google.com/open?id=1AU6__hUHgGQz8_VmlU_2-nlsvcdGvzcX', 'Kathwada', NULL),
(72, '2026-06-04 23:04:03', 'Akash Sathwara', NULL, 'Nexout Digital', 'Digital Marketing', '7041383645', 'akashsathwara1997@gmail.com', 'A- 211 Supath 2 Complex, Near Old Wadaj Bus stand, Ashram Rd, Ahmedabad', NULL, NULL, NULL, '1997-09-20', NULL, NULL, 'https://drive.google.com/open?id=1TWv0NF200NjIF6Dbowkn1MWo2EQr68p1', 'https://drive.google.com/open?id=1w1TWHtONYNf5at3vfBrf1N3GdpNlXaAO', 'https://drive.google.com/open?id=177w0n6B9MEOeQ4_ModUCy-fslbjumMVU', 'Ranip', NULL),
(73, '2026-06-06 16:32:36', 'Dhruvil Khandhala', NULL, 'Medi Dispo Private Limited', 'Personal Care', '9998863947', 'khandhala.d@gmail.com', 'Plot no 360, Road no 7, Kathwada GIDC, Kathwada', NULL, NULL, NULL, '2001-11-19', NULL, NULL, 'https://drive.google.com/open?id=1KKj2IzRjf3kJtlLOCukWGpB9r9fRjauF', 'https://drive.google.com/open?id=1HH-OEz7Tg2pUvLgCRUYKGaMb8BDG4WTz', 'https://drive.google.com/open?id=1yvXsBuekciU-FIlNpX6RILr8hoiSoW9k', 'Nikol', NULL),
(74, '2026-06-06 16:50:21', 'Bharatbhai Popatbhai Dabhi', NULL, 'Sunrise Infra LLP', 'Real Estate', '9979898262', NULL, 'Shreeji Sky Buildcon, Ramol, Ahmedabad', NULL, NULL, NULL, NULL, NULL, NULL, 'https://drive.google.com/open?id=1Lu-eu9lW3usrS7cYCshV10oPWPeqoixu', 'https://drive.google.com/open?id=1rJgMSl0BfSGYyVpmI0DQ4HJ2s3nuZNLx', 'https://drive.google.com/open?id=1EG6DPJDlsklJ1tCsX5ORwIBmb7XAI6li', 'B-21, Krishvilla Banlows, Nr. D Mart, Nikol, Ahmedabad', NULL);

SET FOREIGN_KEY_CHECKS = 1;