CREATE TABLE membership_form (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `timestamp` TEXT NULL,
    `full_name_with_surname` TEXT NULL,
    `designation_in_your_business` TEXT NULL,
    `business_name` TEXT NULL,
    `business_category_i_e_it_construction_travel_automobile_etc` TEXT NULL,
    `mobile` TEXT NULL,
    `email` TEXT NULL,
    `business_address` TEXT NULL,
    `address_area_or_location` TEXT NULL,
    `city` TEXT NULL,
    `native_city` TEXT NULL,
    `birth_date` TEXT NULL,
    `marriage_or_anniversary_date` TEXT NULL,
    `brief_business_introduction` TEXT NULL,
    `profile_picture` TEXT NULL,
    `business_logo` TEXT NULL,
    `attachment_of_membership_payment_rs_1000` TEXT NULL,
    `residence_address_area_or_location` TEXT NULL,
    `document_save_in_folder` TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;